### ISSUE TITLE
2 plugins overlap.

### ISSUE THREAD

**Issue by northeaster** [MickMelon/flarum-ext-coloured-usernames#4]
When I open the "Color Circles" plugin while your plugin is open, your plugin is still open but the colored appearing in the names is going to go. 2 plugins overlap.

**Comment by clarkwinkelmann** [comment]
The problem is with this extension. It's re-using the same initializer name as mine (`clarkwinkelmann-circle-groups`)

A unique initializer name was correctly used in https://github.com/MickMelon/flarum-ext-coloured-usernames/blob/0.1.0/js/src/forum/index.js

However `clarkwinkelmann-circle-groups` is used in the compiled file, I'm suspecting the source files were edited but the re-compilation of the files was forgotten https://github.com/MickMelon/flarum-ext-coloured-usernames/blob/0.1.0/js/dist/forum.js

The solution would be to just run `npm run build`, commit the new dist file and tag a new release.

**Comment by MickMelon** [comment]
Conflict should be sorted now as per https://github.com/MickMelon/flarum-ext-coloured-usernames/pull/7

Thanks
